backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: Title, name: title, widget: string}