backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - label: Blog
    name: blog
    folder: src/pages/blog
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Date, name: date, widget: datetime, date_format: DD.MM.YYYY, time_format: false }
      - { label: Featured Image, name: featuredimage, widget: image }
      - { label: Body, name: body, widget: markdown }