backend:
  name: github
  repo: gideongoddard/freelance-portfolio
  branch: cms

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/home.md"
        fields:
          - {label: Title, name: title, widget: string}